### ISSUE TITLE
Pixelbook上启用之后Android容器不能用了

### ISSUE THREAD

**Issue by Karl15926** [Violin9906/my-ime2#18]
**Describe the bug**
* 启用之后Android容器不能用了，停用之后Android恢复正常

**To Reproduce**

**Expected behavior**
* 可以和Android容器并存……

**Screenshots**
![Screenshot 2020-07-15 at 17.03.33.png](https://i.loli.net/2020/07/15/58PdkGjh9fMmct1.png)
**Desktop (please complete the following information):**
 - OS: [e.g. chrome os 79.0.3945.123] 85.0.4175.0 (Official Build) dev (64-bit)
 - Branch: [e.g. Stable] Dev
 - Software Version [e.g. 1.0.0] 0.0.1

**Additional context**

**Comment by Violin9906** [comment]
啊这，我手上没有官方的chromebook（之前的被我二手出了），都是在chromium虚拟机里测试的，所以定位这个bug可能需要点时间。

**Comment by Violin9906** [comment]
希望你可以更详细的描述一下你遇到的问题，比如：
- 不能用的是Android容器，还是My-IME?
- 如果不能用的是My-IME，那么输入法在Android容器外能否正常工作？
- 如果可以，能否提供启用和未启用安卓容器时，My-IME的Errors页面截图，以供对比？记得在切换安卓容器启用状态后，点击Errors页面的Clear all清空历史错误信息。
- 其他任何你认为有助于我定位bug的信息，比如My-IME的Background控制台输出，等等

**Comment by Karl15926** [comment]
感谢开发者回复，我根据你的问题补充一些信息，希望可以有用。
> * 不能用的是Android容器，还是My-IME?

My-IME是可以正常用的，不能用的是Android容器，My-IME启用后，所有Android App会自动退出且无法再打开，关闭My-IME后重启设备，Android App就可以重新打开了。

> * 如果不能用的是My-IME，那么输入法在Android容器外能否正常工作？

My-IME在Android容器外可以正常工作。

> * 如果可以，能否提供启用和未启用安卓容器时，My-IME的Errors页面截图，以供对比？记得在切换安卓容器启用状态后，点击Errors页面的Clear all清空历史错误信息。

上面我发的截图里，是在正常使用Andoid容器的情况下开启MY-IME后出现的Errors；因为在系统中关闭Android容器会清除Android容器内的所有内容，所以我没法提供未启用Andoid容器时的页面截图。
